name: Karbala Live Stream
on:
  workflow_dispatch: # يسمح لك بتشغيل البث يدوياً
  schedule:
    - cron: '0 */6 * * *' # يعيد تشغيل البث تلقائياً كل 6 ساعات لضمان الاستمرارية

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Install Tools
        run: |
          sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp
          sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Run Streaming Script
        run: |
          # الرابط اللي ردته لبث كربلاء
          URL=$(yt-dlp -f "best[height<=360]" -g "https://www.youtube.com/watch?v=Ds76FCJzLL0")
          
          # إرسال البث لمفتاحك الخاص q12g-s6wc-0y03-0ua5-6e6p
          ffmpeg -re -i "$URL" \
          -c:v libx264 -preset ultrafast -b:v 400k \
          -c:a aac -b:a 128k -ar 44100 \
          -f flv "rtmp://a.rtmp.youtube.com/live2/q12g-s6wc-0y03-0ua5-6e6p"
          
